// <auto-generated />
using System;
using AcunMedyaSportsProject.WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcunMedyaSportsProject.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514122047_miginit")]
    partial class miginit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("int");

                    b.Property<string>("Saloon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.MatchSet", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.HasKey("MatchId", "SetNumber");

                    b.ToTable("MatchSets");
                });

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saloon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.Match", b =>
                {
                    b.HasOne("AcunMedyaSportsProject.WebApi.Entities.Team", "AwayTeam")
                        .WithMany("AwayTeamMatches")
                        .HasForeignKey("AwayTeamId")
                        .IsRequired();

                    b.HasOne("AcunMedyaSportsProject.WebApi.Entities.Team", "HomeTeam")
                        .WithMany("HomeTeamMatches")
                        .HasForeignKey("HomeTeamId")
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.MatchSet", b =>
                {
                    b.HasOne("AcunMedyaSportsProject.WebApi.Entities.Match", "Match")
                        .WithMany("MatchSets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.Match", b =>
                {
                    b.Navigation("MatchSets");
                });

            modelBuilder.Entity("AcunMedyaSportsProject.WebApi.Entities.Team", b =>
                {
                    b.Navigation("AwayTeamMatches");

                    b.Navigation("HomeTeamMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
